Target-template alignment
>P1;EGFR_HUMAN_D0
sequence:EGFR_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
FKKIKVLGSGAFGTVYKGLWIPEGEKVKIPVAIKELREATSPKANKEILDEAYVM--ASVDNPHV--CRLLGICLTSTVQLITQLMP-FGCLLDYVREHKDNIGSQYLLNWCVQIAKGMNYLEDRRLVHRDLAARNVLV---KTPQHVKITDFGLAKLLGAEEKEYHAEGGKVPIK----------WMALESILHRIYTHQSDVWSYGVTVWELMTF--GSKPYDGIPAS----EISSILEKGERLPQPPICT-----IDVYMIMVKCWMIDADSRPKFRELIIEFSKMARDPQRYL*
>P1;KC1D_HUMAN_D0_4KB8_D
structureX:KC1D_HUMAN_D0_4KB8_D:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
YRLGRKIGSGSFGDIYLGTDIAAGEEVAI-----KLECVKTKHPQLHIESKIYKMMQGGVGIPTIRWCGAEG---DYNVMVMELLGPSLEDLFNFCSR---KFSLKTVLLLADQMISRIEYIHSKNFIHRDVKPDNFLMGLGKKGNLVYIIDFGLAKKYRDARTHQH-----IPYRENKNLTGTARYASINTHLGIEQSRRDDLESLG---YVLMYFNLGSLPWQGLKAATKRQKYERISEKKMSTPIEVLCKGYPSEFATYLNF--CRSLRFDDKPDYSYLRQLFRNL-------F*
